models:
  - model-name: liquid/lfm2.5-1.2b
    url: http://host.docker.internal:1234/v1
    is-local: true
  - model-name: qwen/qwen3-coder-next
    url: http://host.docker.internal:1234/v1
    is-local: true
  - name: gpt-5.2
    url: https://api.openai.com/v1
    api-key: $OPENAI_API_KEY
  - name: claude-opus-4-6
    url: https://api.anthropic.com/v1
    api-key: $ANTHROPIC_API_KEY
